#!/bin/sh

if [ -d "$HOME/.vim" ]
then
  read -r -p "$HOME/.vim exists. Delete? [y/N] " response
  if [[ $response =~ ^([yY][eE][sS]|[yY])$ ]]
  then
    rm -rf $HOME/.vim
  else
    exit
  fi
fi

if [ -f "$HOME/.vimrc" ]
then
  read -r -p "$HOME/.vimrc exists. Delete? [y/N] " response
  if [[ $response =~ ^([yY][eE][sS]|[yY])$ ]]
  then
    rm $HOME/.vimrc
  else
    exit
  fi
fi


ln -s `pwd` $HOME/.vim
ln -s `pwd`/vimrc $HOME/.vimrc

echo "Installing Vim Plug"
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

vim +PlugInstall +qall
