#!/bin/sh

git submodule init
git submodule update

if [ -d "$HOME/.vim" ]
then
  read -r -p "$HOME/.vim exists. Delete? [y/N] " response
  if [[ $response =~ ^([yY][eE][sS]|[yY])$ ]]
  then
    rm -rf $HOME/.vim
  else
    exit
  fi
fi

if [ -f "$HOME/.vimrc" ]
then
  read -r -p "$HOME/.vimrc exists. Delete? [y/N] " response
  if [[ $response =~ ^([yY][eE][sS]|[yY])$ ]]
  then
    rm $HOME/.vimrc
  else
    exit
  fi
fi

ln -s `pwd` $HOME/.vim
ln -s `pwd`/vimrc $HOME/.vimrc
vim +BundleInstall +qall

echo "To get the proper font please run"
echo "> brew tap caskroom/fonts"
echo "> brew cask install font-inconsolata-for-powerline"
